// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ping": {
            "get": {
                "description": "Returns API status and availability of dependent microservices (Collector, Subscriber)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Checking the service status (Healthcheck)",
                "responses": {
                    "200": {
                        "description": "All systems are working fine",
                        "schema": {
                            "$ref": "#/definitions/v1.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "One or more services are unavailable",
                        "schema": {
                            "$ref": "#/definitions/v1.HealthResponse"
                        }
                    }
                }
            }
        },
        "/v1/repositories/info": {
            "get": {
                "description": "Returns data about stars, forks, and the repository description by its URL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Gets information about GitHub repository",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GitHub URL (e.g. https://github.com/google/go-github)",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.RepositoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Repository not found"
                }
            }
        },
        "v1.HealthResponse": {
            "type": "object",
            "properties": {
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.ServiceStatus"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "v1.RepositoryResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2014-08-19T22:33:41Z"
                },
                "description": {
                    "type": "string",
                    "example": "The Go programming language"
                },
                "forks": {
                    "type": "integer",
                    "example": 12345
                },
                "full_name": {
                    "type": "string",
                    "example": "go"
                },
                "html_url": {
                    "type": "string",
                    "example": "https://github.com/golang/go"
                },
                "stars": {
                    "type": "integer",
                    "example": 123456
                }
            }
        },
        "v1.ServiceStatus": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "processor"
                },
                "status": {
                    "type": "string",
                    "example": "up"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Repo Stat API",
	Description:      "A service for collecting information of GitHub repositories.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
