// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/subscriber/subscriber.proto

package subscriberv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscriber_subscriber_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscriber_subscriber_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscriber_subscriber_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *SubscribeRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscriber_subscriber_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubscribeResponse) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *SubscribeResponse) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscriber_subscriber_proto_rawDescGZIP(), []int{4}
}

func (x *UnsubscribeRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *UnsubscribeRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type UnsubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeResponse) Reset() {
	*x = UnsubscribeResponse{}
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeResponse) ProtoMessage() {}

func (x *UnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscriber_subscriber_proto_rawDescGZIP(), []int{5}
}

func (x *UnsubscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscriber_subscriber_proto_rawDescGZIP(), []int{6}
}

type ListResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Subscriptions []*ListResponse_Subscription `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscriber_subscriber_proto_rawDescGZIP(), []int{7}
}

func (x *ListResponse) GetSubscriptions() []*ListResponse_Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type ListResponse_Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse_Subscription) Reset() {
	*x = ListResponse_Subscription{}
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse_Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse_Subscription) ProtoMessage() {}

func (x *ListResponse_Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse_Subscription.ProtoReflect.Descriptor instead.
func (*ListResponse_Subscription) Descriptor() ([]byte, []int) {
	return file_proto_subscriber_subscriber_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListResponse_Subscription) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ListResponse_Subscription) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

var File_proto_subscriber_subscriber_proto protoreflect.FileDescriptor

const file_proto_subscriber_subscriber_proto_rawDesc = "" +
	"\n" +
	"!proto/subscriber/subscriber.proto\x12\rsubscriber.v1\"\r\n" +
	"\vPingRequest\"$\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"<\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"M\n" +
	"\x11SubscribeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x03 \x01(\tR\x04repo\">\n" +
	"\x12UnsubscribeRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"/\n" +
	"\x13UnsubscribeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\r\n" +
	"\vListRequest\"\x98\x01\n" +
	"\fListResponse\x12N\n" +
	"\rsubscriptions\x18\x01 \x03(\v2(.subscriber.v1.ListResponse.SubscriptionR\rsubscriptions\x1a8\n" +
	"\fSubscription\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo2\xb4\x02\n" +
	"\n" +
	"Subscriber\x12?\n" +
	"\x04Ping\x12\x1a.subscriber.v1.PingRequest\x1a\x1b.subscriber.v1.PingResponse\x12N\n" +
	"\tSubscribe\x12\x1f.subscriber.v1.SubscribeRequest\x1a .subscriber.v1.SubscribeResponse\x12T\n" +
	"\vUnsubscribe\x12!.subscriber.v1.UnsubscribeRequest\x1a\".subscriber.v1.UnsubscribeResponse\x12?\n" +
	"\x04List\x12\x1a.subscriber.v1.ListRequest\x1a\x1b.subscriber.v1.ListResponseBSZQgithub.com/IliaSotnikov2005/golang-course/task5/repo-stat/subscriber;subscriberv1b\x06proto3"

var (
	file_proto_subscriber_subscriber_proto_rawDescOnce sync.Once
	file_proto_subscriber_subscriber_proto_rawDescData []byte
)

func file_proto_subscriber_subscriber_proto_rawDescGZIP() []byte {
	file_proto_subscriber_subscriber_proto_rawDescOnce.Do(func() {
		file_proto_subscriber_subscriber_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_subscriber_subscriber_proto_rawDesc), len(file_proto_subscriber_subscriber_proto_rawDesc)))
	})
	return file_proto_subscriber_subscriber_proto_rawDescData
}

var file_proto_subscriber_subscriber_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_subscriber_subscriber_proto_goTypes = []any{
	(*PingRequest)(nil),               // 0: subscriber.v1.PingRequest
	(*PingResponse)(nil),              // 1: subscriber.v1.PingResponse
	(*SubscribeRequest)(nil),          // 2: subscriber.v1.SubscribeRequest
	(*SubscribeResponse)(nil),         // 3: subscriber.v1.SubscribeResponse
	(*UnsubscribeRequest)(nil),        // 4: subscriber.v1.UnsubscribeRequest
	(*UnsubscribeResponse)(nil),       // 5: subscriber.v1.UnsubscribeResponse
	(*ListRequest)(nil),               // 6: subscriber.v1.ListRequest
	(*ListResponse)(nil),              // 7: subscriber.v1.ListResponse
	(*ListResponse_Subscription)(nil), // 8: subscriber.v1.ListResponse.Subscription
}
var file_proto_subscriber_subscriber_proto_depIdxs = []int32{
	8, // 0: subscriber.v1.ListResponse.subscriptions:type_name -> subscriber.v1.ListResponse.Subscription
	0, // 1: subscriber.v1.Subscriber.Ping:input_type -> subscriber.v1.PingRequest
	2, // 2: subscriber.v1.Subscriber.Subscribe:input_type -> subscriber.v1.SubscribeRequest
	4, // 3: subscriber.v1.Subscriber.Unsubscribe:input_type -> subscriber.v1.UnsubscribeRequest
	6, // 4: subscriber.v1.Subscriber.List:input_type -> subscriber.v1.ListRequest
	1, // 5: subscriber.v1.Subscriber.Ping:output_type -> subscriber.v1.PingResponse
	3, // 6: subscriber.v1.Subscriber.Subscribe:output_type -> subscriber.v1.SubscribeResponse
	5, // 7: subscriber.v1.Subscriber.Unsubscribe:output_type -> subscriber.v1.UnsubscribeResponse
	7, // 8: subscriber.v1.Subscriber.List:output_type -> subscriber.v1.ListResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_subscriber_subscriber_proto_init() }
func file_proto_subscriber_subscriber_proto_init() {
	if File_proto_subscriber_subscriber_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_subscriber_subscriber_proto_rawDesc), len(file_proto_subscriber_subscriber_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_subscriber_subscriber_proto_goTypes,
		DependencyIndexes: file_proto_subscriber_subscriber_proto_depIdxs,
		MessageInfos:      file_proto_subscriber_subscriber_proto_msgTypes,
	}.Build()
	File_proto_subscriber_subscriber_proto = out.File
	file_proto_subscriber_subscriber_proto_goTypes = nil
	file_proto_subscriber_subscriber_proto_depIdxs = nil
}
