services:
  collector:
    build:
      context: ./repo-stat
      dockerfile: ./Dockerfile.collector
    container_name: collector
    ports:
      - "8081:8081"
    volumes:
      - ./repo-stat/collector/config/config.yaml:/config/config.yaml
    network_mode: host
  processor:
    build:
      context: ./repo-stat
      dockerfile: ./Dockerfile.processor
    container_name: processor
    ports:
      - "8082:8082"
    volumes:
      - ./repo-stat/processor/config/config.yaml:/config/config.yaml
    depends_on:
      - collector
    network_mode: host
  api:
    build:
      context: ./repo-stat
      dockerfile: ./Dockerfile.api
    container_name: api
    ports:
      - "8080:8080"
    volumes:
      - ./repo-stat/api/config/config.yaml:/config/config.yaml
    depends_on:
      - processor
      - subscriber
    network_mode: host
  subscriber:
    build:
      context: ./repo-stat
      dockerfile: ./Dockerfile.subscriber
    container_name: subscriber
    ports:
      - "8083:8083"
    volumes:
      - ./repo-stat/subscriber/config/config.yaml:/config/config.yaml
    network_mode: host
  tests:
    image: tests:latest
    build:
      context: tests
    container_name: tests
    restart: "no"
    depends_on:
      - api
    network_mode: host
    # entrypoint: ["true"]
