// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Repository struct {
	FullName    string
	Description pgtype.Text
	Stargazers  int32
	Forks       int32
	CreatedAt   pgtype.Timestamptz
	HtmlUrl     pgtype.Text
	LastCached  pgtype.Timestamptz
}
