log-level: "DEBUG"

github:
  baseurl: "https://api.github.com/repos"
  timeout_seconds: 10
  user-agent: "Collector-Service/1.0"

subscriber:
  address: "localhost:8083"

kafka:
  brokers: ["localhost:9092"]
  requests_topic: "repository_requests" # Слушает запросы от Sub и Proc
  results_topic: "repository_results"
  group_id: "processor_group"
