// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetRepository(ctx context.Context, fullName string) (Repository, error)
	ListAllRepositories(ctx context.Context) ([]Repository, error)
	UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) error
}

var _ Querier = (*Queries)(nil)
