// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRepository = `-- name: GetRepository :one
SELECT full_name, description, stargazers, forks, created_at, html_url, last_cached FROM repositories
WHERE full_name = $1 LIMIT 1
`

func (q *Queries) GetRepository(ctx context.Context, fullName string) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepository, fullName)
	var i Repository
	err := row.Scan(
		&i.FullName,
		&i.Description,
		&i.Stargazers,
		&i.Forks,
		&i.CreatedAt,
		&i.HtmlUrl,
		&i.LastCached,
	)
	return i, err
}

const upsertRepository = `-- name: UpsertRepository :exec
INSERT INTO repositories (
    full_name, description, stargazers, forks, created_at, html_url, last_cached
) VALUES (
    $1, $2, $3, $4, $5, $6, CURRENT_TIMESTAMP
)
ON CONFLICT (full_name) DO UPDATE SET
    description = EXCLUDED.description,
    stargazers = EXCLUDED.stargazers,
    forks = EXCLUDED.forks,
    html_url = EXCLUDED.html_url,
    last_cached = CURRENT_TIMESTAMP
`

type UpsertRepositoryParams struct {
	FullName    string
	Description pgtype.Text
	Stargazers  int32
	Forks       int32
	CreatedAt   pgtype.Timestamptz
	HtmlUrl     pgtype.Text
}

func (q *Queries) UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) error {
	_, err := q.db.Exec(ctx, upsertRepository,
		arg.FullName,
		arg.Description,
		arg.Stargazers,
		arg.Forks,
		arg.CreatedAt,
		arg.HtmlUrl,
	)
	return err
}
